---
- name: "Docker | Install in Debian based Distros"
  ansible.builtin.include_tasks: debian_based.yaml
  when: ansible_os_family == 'Debian'
  tags: ["docker"]

- name: "Docker | Install in RHEL based Distros"
  ansible.builtin.include_tasks: rhel_based.yaml
  when: ansible_os_family == 'RedHat'
  tags: ["docker"]
