---
- name: "Add Docker repository"
  ansible.builtin.command:
    cmd: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  changed_when: false

- name: "Install Docker engine and compose"
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: "Add Docker daemon.json"
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    mode: "0644"
    owner: root
    group: root
  notify:
    - "Restart docker"

- name: "Start docker"
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true

- name: "Set cronjob to cleanup system"
  ansible.builtin.cron:
    name: "docker system prune"
    state: present
    minute: "0"
    hour: "0"
    user: root
    job: "/usr/bin/timeout --preserve-status -s 9 5m /usr/bin/docker system prune -a -f"
